{{- if not .Values.security.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sessionfs.secretsName" . }}
  labels:
    {{- include "sessionfs.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.security.verificationSecret }}
  verification-secret: {{ .Values.security.verificationSecret | b64enc | quote }}
  {{- else }}
  verification-secret: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.security.encryptionKey }}
  encryption-key: {{ .Values.security.encryptionKey | b64enc | quote }}
  {{- else }}
  encryption-key: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.email.resendApiKey }}
  resend-api-key: {{ .Values.email.resendApiKey | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sessionfs.postgresql.fullname" . }}
  labels:
    {{- include "sessionfs.componentLabels" (list . "postgresql") | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ .Values.postgresql.auth.secretKeys.usernameKey }}: {{ .Values.postgresql.auth.username | b64enc | quote }}
  {{- if .Values.postgresql.auth.password }}
  {{ .Values.postgresql.auth.secretKeys.passwordKey }}: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- else }}
  {{ .Values.postgresql.auth.secretKeys.passwordKey }}: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
{{- end }}
